// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://micctjmnojsonnqjgpnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pY2N0am1ub2pzb25ucWpncG5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTA2ODksImV4cCI6MjA3NDM2NjY4OX0.NVlz_XCNDk8NrYaMGN5jgcNHIvLUtAp8zo0pKRyKLBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});